### ISSUE TITLE
Suggestion/Ideas aboud UI/UX improvement. 

### ISSUE THREAD

**Issue by minhaz1217** [thekhairul/citybusbd#3]
1. The search and found 2 bus texts should be in bangla as well as english.
![image](https://github.com/user-attachments/assets/100b2a3e-1536-43df-9bf2-d86b79259a12)

2. It'd be helpful if the names are also in bangla as well.
![image](https://github.com/user-attachments/assets/0fae9602-fdb9-4153-8208-06d499cd9f2f)

3. There is no gap while the details is hidden, but there is a gap while the detail tab is open.
![image](https://github.com/user-attachments/assets/40d02072-3a96-4702-aa8a-07114977ea1b)
![image](https://github.com/user-attachments/assets/0b64bb08-2364-4156-9e11-a2b87801d092)

4. the taka icon is smaller than the route icon, they should be same.
![image](https://github.com/user-attachments/assets/7a7789ce-199f-42bc-990e-404a9b3eff59)

5. An error occurs when selecting the same To and From, selecting the same field should be disabled. 
![image](https://github.com/user-attachments/assets/611a858a-fbda-47c6-9668-6db380c728f0)

6. An easy button to swipe the fields. Like to will be from and from will be to. Basically other direction.

7. If no data is found then it is showing a toast only, it should be visible all the time so that people who got distracted during the search don't miss it.
![image](https://github.com/user-attachments/assets/982f0a5c-814b-4c21-aa10-04ffbf6aad30)

8. It would be great it you can detect before pressing the search which routes are possible. There are 0 bus in the list that goes from Bangla motor to postogola. So when someone selects Banglamoto then from the other field postogola should be disabled. Or something similar.

9. If the cost is estimated and not based on the Govt. published list, then it should say so. Otherwise people using the website may get confused and it can cause issues. If it is based on the Govt. published list, then it should also say that and mention the version. IE. the document identification number or date of approval.
![image](https://github.com/user-attachments/assets/abd39cb3-2d0b-40d6-a6d6-7af821d0cd36)

Anyway... awesome website, great initiative. I'm just nitpicking. Let me know if you need help with implementing any of these. If you need help with data modeling or entering data let me know as well.

**Comment by thekhairul** [comment]
Thanks. I'm grateful that you put such effort into making the app better. I've gone through the issues and made following decisions:

1 - less important. doesn't affect the UX that much at the moment. we'll think about full translation later
2 - same as 1
3 - less important. it's default behavior of MUI accordion. I think UX is same with or without the gap
4 - fairly important. will fix it when more pressing tasks are done
5 - extremely important. will fix it ASAP
6 - fairly important. will implement it when more pressing tasks are done
7 - sounds important. do you mean we should remove the timeout of the toast and let the user close it?
8 - I think the ROI will not suffice. for now let's keep it that way. user will see the 'Not found' toast if no bus is available for their search
9 - Extremely important. will work on it ASAP

If you want you can pick up 4 and 6. if you do, please create separate issue and feature branch for each of them.
